[package]
name = "osx-amd-kvm"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "fs", "sync"] }
async-trait = "0.1"
tokio-stream = "0.1"
semver = "1.0.26"
thiserror = "2.0.12"

[dev-dependencies]
tempfile = "3.10"
