name: Rust Code Coverage

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev, staging ]

jobs:
  coverage:
    name: Generate Code Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for gh-pages deployment
      pull-requests: write  # Required for PR comments
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest
          use-tool-cache: true

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Build and run tests with coverage
        env:
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage"
          RUSTDOCFLAGS: "-Cinstrument-coverage"
        run: cargo test --workspace

      - name: Generate coverage reports
        run: |
          # Create coverage directory
          mkdir -p target/coverage-report
          
          # Generate coverage reports (HTML and cobertura)
          grcov target/coverage \
            --binary-path ./target/debug \
            --source-dir ./crates/** \
            --output-path target/coverage-report \
            --ignore-not-existing \
            --branch \
            --output-types html,cobertura

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          COVERAGE=$(xmllint --xpath "concat('Coverage: ', 100 * string(//coverage/@line-rate), '%')" "target/coverage-report/cobertura.xml")
          echo "Coverage: $COVERAGE"
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          
          # Calculate numeric value for badge
          COVERAGE_PCT=$(xmllint --xpath "100 * string(//coverage/@line-rate)" "target/coverage-report/cobertura.xml")
          COVERAGE_INT=$(printf "%.0f" $COVERAGE_PCT)
          
          # Colors based on coverage: red < 50% < orange < 70% < yellow < 80% < green
          if [ $COVERAGE_INT -lt 50 ]; then
            COLOR=red
          elif [ $COVERAGE_INT -lt 70 ]; then
            COLOR=orange
          elif [ $COVERAGE_INT -lt 80 ]; then
            COLOR=yellow
          else
            COLOR=green
          fi
          
          # Create a coverage.json file for shields.io
          echo "{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${COVERAGE_INT}%\",\"color\":\"${COLOR}\"}" > "target/coverage-report/coverage.json"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/coverage-report/
          if-no-files-found: error

      - name: Deploy coverage to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/coverage-report
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update coverage report'

      - name: Compare with Previous Coverage
        if: github.event_name == 'pull_request'
        id: prev-coverage
        run: |
          REPO="${GITHUB_REPOSITORY}"
          MAIN_BRANCH_COVERAGE=$(curl -s "https://raw.githubusercontent.com/${REPO}/main/coverage.json" | jq -r '.message' 2>/dev/null || echo "N/A")
          
          if [[ "$MAIN_BRANCH_COVERAGE" != "N/A" ]]; then
            CURRENT_COVERAGE=$(xmllint --xpath "100 * string(//coverage/@line-rate)" target/coverage-report/cobertura.xml)
            CURRENT_COVERAGE_ROUNDED=$(printf "%.1f" $CURRENT_COVERAGE)
            
            MAIN_COVERAGE_NUM=$(echo $MAIN_BRANCH_COVERAGE | sed 's/%//')
            
            DIFF=$(echo "$CURRENT_COVERAGE_ROUNDED - $MAIN_COVERAGE_NUM" | bc)
            
            if (( $(echo "$DIFF >= 0" | bc -l) )); then
              DIFF_FORMATTED="+$DIFF%"
            else
              DIFF_FORMATTED="$DIFF%"
            fi
            
            echo "diff=$DIFF_FORMATTED" >> $GITHUB_OUTPUT
          else
            echo "diff=N/A" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Code Coverage Report
            ${{ steps.extract-coverage.outputs.coverage }}
            Change: ${{ steps.prev-coverage.outputs.diff }}
            
            [Full HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          edit-mode: replace
          comment-id: ${{ github.event.pull_request.number }}-coverage